# Generated by Django 2.2.10 on 2020-05-01 03:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=10)),
                ('author_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('headshot', models.ImageField(upload_to='author_headshots')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('', 'Choose'), ('Politics', 'Politics'), ('Health', 'Health'), ('Environment', 'Environment'), ('Entertainment', 'Entertainment')], default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_title', models.CharField(max_length=30)),
                ('expiration', models.DateField()),
                ('number_of_news', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('status', models.CharField(choices=[('', 'Choose'), ('Resolved', 'Resolved'), ('Pending', 'Pending')], default='', max_length=30)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=60)),
                ('state_province', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Location')),
            ],
            options={
                'ordering': ['-publisher_name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('link', models.URLField()),
                ('status', models.CharField(choices=[('', 'Choose'), ('Pending', 'Pending'), ('Staged', 'Staged')], default='', max_length=30)),
                ('upvotes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Heading')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Location')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Publisher')),
            ],
        ),
        migrations.AddField(
            model_name='heading',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Location'),
        ),
    ]
