# Generated by Django 2.2.10 on 2020-05-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.Author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.Location'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.Publisher'),
        ),
    ]
