# Generated by Django 2.2.10 on 2020-05-24 11:51

from django.db import migrations
import django.db.models.deletion
from django.contrib.postgres.operations import UnaccentExtension
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200524_1944'),
    ]

    operations = [
    	TrigramExtension(),
    	UnaccentExtension(),
    ]
