# Generated by Django 2.2.10 on 2020-05-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_author_headshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='heading_title',
            field=models.CharField(max_length=250),
        ),
    ]
