# Generated by Django 2.2.10 on 2020-05-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200509_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='heading_title',
            field=models.CharField(max_length=30),
        ),
    ]
