# Generated by Django 2.2.10 on 2020-05-11 11:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200510_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heading',
            name='downvotes',
        ),
        migrations.AlterField(
            model_name='heading',
            name='heading_title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CounterHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterheading_title', models.CharField(max_length=50)),
                ('counter_expiration', models.DateField()),
                ('counter_number_of_news', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('counter_status', models.CharField(choices=[('', 'Choose'), ('Resolved', 'Resolved'), ('Pending', 'Pending')], default='', max_length=30)),
                ('counter_upvotes', models.IntegerField(default=0)),
                ('counter_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
                ('counter_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Location')),
            ],
        ),
    ]
